// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7XInvtkcZx2ugpevmxKSg_XsXPVn-AqA',
    appId: '1:787155515986:web:522cef8b8b53fdcdc63d8b',
    messagingSenderId: '787155515986',
    projectId: 'musicmapp-a3cfd',
    authDomain: 'musicmapp-a3cfd.firebaseapp.com',
    databaseURL: 'https://musicmapp-a3cfd-default-rtdb.firebaseio.com',
    storageBucket: 'musicmapp-a3cfd.appspot.com',
    measurementId: 'G-E7G2S430B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx6HfIertSwd0HyBF2yZsF42pSwMz5GMo',
    appId: '1:787155515986:android:3e8a1495a1e26bddc63d8b',
    messagingSenderId: '787155515986',
    projectId: 'musicmapp-a3cfd',
    databaseURL: 'https://musicmapp-a3cfd-default-rtdb.firebaseio.com',
    storageBucket: 'musicmapp-a3cfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgR8JlaSFdc5qEOJpD6UhOoKYzWveOlu0',
    appId: '1:787155515986:ios:95e72ef97e5a9353c63d8b',
    messagingSenderId: '787155515986',
    projectId: 'musicmapp-a3cfd',
    databaseURL: 'https://musicmapp-a3cfd-default-rtdb.firebaseio.com',
    storageBucket: 'musicmapp-a3cfd.appspot.com',
    iosClientId: '787155515986-92ikb9rigjh043dcjfs8r8j64apvkj08.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicmapp4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgR8JlaSFdc5qEOJpD6UhOoKYzWveOlu0',
    appId: '1:787155515986:ios:491b0997f23e5291c63d8b',
    messagingSenderId: '787155515986',
    projectId: 'musicmapp-a3cfd',
    databaseURL: 'https://musicmapp-a3cfd-default-rtdb.firebaseio.com',
    storageBucket: 'musicmapp-a3cfd.appspot.com',
    iosClientId: '787155515986-bj0950j862j9nrdcgmso6s8c2olrshmf.apps.googleusercontent.com',
    iosBundleId: 'macosmusicmapp.package',
  );
}
